### ISSUE TITLE
Weird PYTHONPATH workaround on Linux

### ISSUE THREAD

**Issue by pllim** [SaraOgaz/STScI-env#14]
So, I have "Institute Linux" with no root access. When I installed Anaconda, I had to modify my PATH and PYTHONPATH to pick it up. My root Anaconda environment happens to be Python 2.7 (for historical reasons). I found out that after I created a new environment with Python 3, I need to do two steps (in bash) to switch to Python 3 environment properly:

```
unset PYTHONPATH
source activate py3env
```

Did I do something wrong? If not, maybe this is worth documenting? Not sure.

**Comment by SaOgaz** [comment]
I'm not sure about this, can I not tag Joe if he hasn't commented on here before?  his @jhunkeler isn't highlighted like they normally are...

**Comment by SaOgaz** [comment]
Okay... now it is?

**Comment by pllim** [comment]
Might be a server hiccup. I can see his tag.

**Comment by jhunkeler** [comment]
@pllim To use Anaconda you shouldn't need to set `PYTHONPATH`. If you set `PYTHONPATH` to point to the `root` environment conda's internal virtualenvs will stop functioning. You can set PYTHONPATH to point to a directory containing your own modules in a directory far-far away, but definitely not Anaconda itself.

EDIT: "plim" must hate me by now :smiling_imp:

**Comment by pllim** [comment]
There are _two_ L's in my username :sweat_smile:

**Comment by pllim** [comment]
Okay, that works! The `PYTHONPATH` confusion was inherited from old setup. Thanks!
