### ISSUE TITLE
Advertise link to the RTD doc

### ISSUE THREAD

**Issue by pllim** [SaraOgaz/STScI-env#19]
I propose adding a `README` file (RST, MD, whatever format you like) that advertises http://stsci-env.readthedocs.io/en/latest/ on this GitHub repo. 

If you want to get fancy, you can even add a badge -- http://read-the-docs.readthedocs.io/en/latest/badges.html

**Comment by SaOgaz** [comment]
Forgot to tag, but I've added this now.  Thanks!
