### ISSUE TITLE
Wrong tar command?

### ISSUE THREAD

**Issue by pllim** [SaraOgaz/STScI-env#3]
```
tar cfz envbackup.tar.gz .profile, .bash*
```

Is there supposed to be a whitespace between `.profile,` and `.bash*`? Did you test it out?

**Comment by jhunkeler** [comment]
> tar cfz envbackup.tar.gz .profile, .bash*

The comma between `.profile` and `.bash*` needs to go too.

**Comment by SaOgaz** [comment]
Fixed! Should I be tagging some part of the code when I close these?

**Comment by pllim** [comment]
Well, I _think_ a commit push will automatically close the issue if you say "fix #3" in the commit message? Obviously, you need to replace that number with the real issue number.
