### ISSUE TITLE
Make command syntax consistent (remove the leading ">")

### ISSUE THREAD

**Issue by pllim** [SaraOgaz/STScI-env#4]
In http://bashconda.readthedocs.io/en/latest/bash_setup.html:

Should probably replace:

```
>rm ~/.profile
>rm ~/.bash*
```

with:

```
rm ~/.profile
rm ~/.bash*
```

This is because other commands on that page did not include a prompt. This also occur in other parts of the document.

**Comment by SaOgaz** [comment]
I got rid of all references in code blocks to a shell beginning character, although i left the one's for the set up testing in, will come back and close this comment when that part is resolved.
