### ISSUE TITLE
Here is the blackhole_env.sh

### ISSUE THREAD

**Issue by pllim** [SaraOgaz/STScI-env#6]
This should solve your "todo" for http://bashconda.readthedocs.io/en/latest/installing_anaconda.html#step-4-quick-test-to-see-if-your-setup-was-succesful

`blackhole_env.sh`:

```
#!/bin/bash
NEW_HOME=/home/username
[[ "$USER" != "" ]] && exec -c $0
export HOME=$NEW_HOME
export TERM=xterm
source /etc/profile
export PATH=$HOME/anaconda/bin:$PATH
```

**Comment by jhunkeler** [comment]
I also created something people could just run as a script, since you ultimately have to source `blackhole_env.sh` in order to reap its benefits:

```
/grp/hst/ssb/blackhole/interactive.sh
```

To test their environment they can run `source ~/.bash_profile`. When they're done testing they can `exit` to return to their previous shell.

**Comment by SaOgaz** [comment]
Added this in.
