### ISSUE TITLE
Document this weird case (for Astroconda env with IRAF)?

### ISSUE THREAD

**Issue by pllim** [SaraOgaz/STScI-env#7]
I ran into a problem where my anaconda env cannot start IRAF because `$iraf` is set wrongly. It turns out to be cause by me reprogramming how `cd` command works in my `~/.bash.myalias` as such:

```
function cd {
    old=$PWD && builtin cd "$@" && echo $PWD":" && ls
}
```

The solution is to comment/remove that incantation.

p.s. There is also a problem with STScI Linux machines not having `libncurses.so.5` needed to run IRAF but @jhunkeler said he is going to take care of that.

**Comment by SaOgaz** [comment]
Do you think there are many people who have aliased their `cd` command?  It seems like kind of an unusual case to me, but maybe it's not...

**Comment by pllim** [comment]
Are you saying that I'm weird? :joy: (Maybe yes...)

You can ignore this if you want. But if you have a section for "we have solutions for these weird situations", then this is a good fit there.

**Comment by SaOgaz** [comment]
We're going to have an FAQ section on this page, I will add this if we get a second case of it :D
